[package]
authors = ["The RustWasm Developers"]
categories = ["wasm"]
description = "My awesome Yew with Yew-Router and Parcel application!"
license = "Apache-2.0/MIT"
name = "yew-parcel"
edition = '2018'
readme = "./README.md"
repository = "https://github.com/spielrs/yew-parcel-template.git"
version = "0.13.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "0.1"
wasm-bindgen = { version="0.2", features=["serde-serialize"]}
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = { version = "0.4", optional = true }
serde = "1.0"
serde_derive = "1.0"
dotenv = "0.15"
failure = "0.1"
web-sys = { version= "0.3", features=["HtmlInputElement","WebSocket","HtmlSelectElement","DomRect", "Element", "Window", "CssStyleDeclaration"]}
log = "0.4.6"
wasm-logger = "0.2.0"
serde_json = "1.0.48"
js-sys = "0.3.36"
maplit = "1.0.2"
vt100 = "0.8.1"
gloo = "0.2.1"
lazy_static = "1.4.0"
# regex = "1.3.6"
# rusty_term = { path = "../../rusty_term"}
#
# [dependencies.rusty_term]
# path = "../../rusty_term"

[dependencies.yew]
version = "0.14"
features = ["web_sys"]
path = "../../yew"

[build]
target="wasm32-unknown-unknown"
